# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdreflow" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "827ac9a55112c64df6fb6d3c06e67ca474e7239489d33f11e74f910280c9708e"
      url "https://github.com/jbeda/mdreflow/releases/download/v#{version}/mdreflow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4424a57c05c8951b1476de71bd41ccd4769e64bb309eed8ace665b2b87f38bd6"
      url "https://github.com/jbeda/mdreflow/releases/download/v#{version}/mdreflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "350d3a44adffd6ef3864e2f1f2a13ea0f2d13e3bd8bb8f30ef1b836299814dcf"
      url "https://github.com/jbeda/mdreflow/releases/download/v#{version}/mdreflow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "284f9eed8670e706de43b339a6c0727d97b7919dda78783e1302f4245d9e3bb8"
      url "https://github.com/jbeda/mdreflow/releases/download/v#{version}/mdreflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mdreflow"
  desc "Reflow Markdown prose: sentence-per-line semantic line breaks by default"
  homepage "https://github.com/jbeda/mdreflow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdreflow"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdreflow"]
    end
  end

  # No zap stanza required

end
