# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdreflow" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "f5978414e898457129414b3d7228bcf3648f21068ab54a1a8568a3d6969126c5"
      url "https://github.com/jbeda/mdreflow/releases/download/v#{version}/mdreflow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6164208819810cdc340b2cb15d4c9a1f04bd737c37a227b039c62e54b1fb89e7"
      url "https://github.com/jbeda/mdreflow/releases/download/v#{version}/mdreflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eb33c7b88e9914b90ea94b4674f880afec340a936189eb1116ee2753a2fecfe0"
      url "https://github.com/jbeda/mdreflow/releases/download/v#{version}/mdreflow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f3011fcacce0a500d53dce6b5977fdf0e0a1c52d6730b9b50461c4f93493844e"
      url "https://github.com/jbeda/mdreflow/releases/download/v#{version}/mdreflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mdreflow"
  desc "Reflow Markdown prose: sentence-per-line semantic line breaks by default"
  homepage "https://github.com/jbeda/mdreflow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdreflow"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdreflow"]
    end
  end

  # No zap stanza required

end
