# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdreflow" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "b4a6d75bde5fa6a452b6fe88eba6d21bcba1d962fb2e95939ca1f01b9557ccbe"
      url "https://github.com/jbeda/mdreflow/releases/download/v#{version}/mdreflow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dd39c3082516e035cade82da62f764c3d925a1be77b0aaf478dc7637824118d7"
      url "https://github.com/jbeda/mdreflow/releases/download/v#{version}/mdreflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6eb8cf043d903911610be1bd77fad449d9dad22ad3a4d3db0dddd91bcd46858a"
      url "https://github.com/jbeda/mdreflow/releases/download/v#{version}/mdreflow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f2bfdcb9f5514db35af4798af52848945fd356e0b04b7c45dd47756833366a9e"
      url "https://github.com/jbeda/mdreflow/releases/download/v#{version}/mdreflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mdreflow"
  desc "Reflow Markdown prose: sentence-per-line semantic line breaks by default"
  homepage "https://github.com/jbeda/mdreflow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdreflow"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdreflow"]
    end
  end

  # No zap stanza required

end
